import { FLOW_STATES, type FlowState } from "@bos/shared";
import type { PageProbeReport, ProbedElement } from "./pageProbe";

export const FLOW_SIGNALS = {
  loginUrl: /accounts\.google\.com|consent\.google\.com|\/signin|\/ServiceLogin|\/AccountChooser|\/o\/oauth2\//i,
  loginText: [/^sign in$/i,/sign in to continue/i,/sign in with google/i,/continue with google/i,/choose an account/i,/use another account/i,/^log in$/i,/verify it['’]s you/i,/couldn['’]t sign you in/i,/to continue to .*flow/i],
  landingCta: [/create with (google )?flow/i,/try (google )?flow/i,/start creating/i,/^get started$/i,/^open flow$/i,/^try it now$/i],
  // Current Flow home (Aug 2026) renders the tile as "+ New project". Keep
  // matching semantic text rather than a brittle generated CSS class.
  workspaceCta: [/^\s*\+?\s*new project\s*$/i,/^\s*\+?\s*new video\s*$/i,/create (a )?new project/i,/^untitled project$/i,/^start a new project$/i],
  workspaceText: [/my projects/i,/your projects/i,/recent projects/i,/^projects$/im,/flow tv/i,/flow music/i],
  promptHint: [/generate a video/i,/describe (your|the)/i,/prompt/i,/what do you want/i,/type (a|your)/i,/create a video/i,/your idea/i,/^ask flow/i,/text to video/i,/scene description/i],
  searchHint: [/^search$/i,/search projects/i,/search\b/i],
  submitHint: [/^generate$/i,/^create$/i,/^send$/i,/^submit$/i,/generate video/i,/^run$/i,/^go$/i,/arrow_upward/i,/^send (message|prompt)$/i],
  submitAvoid: [/cancel/i,/close/i,/back/i,/settings/i,/help/i,/feedback/i,/sign out/i,/delete/i,/^clear$/i],
  generatingText: [/generating/i,/creating your video/i,/rendering/i,/processing/i,/working on it/i,/this (may|can|will) take/i,/in progress/i,/^queued$/i,/please wait/i],
  readyText: [/your video is ready/i,/^download$/i,/generation complete/i,/^add to scene$/i,/^extend$/i],
  errorText: [/something went wrong/i,/try again later/i,/an error occurred/i,/failed to generate/i,/generation failed/i,/out of (credits|generations)/i,/you['’ ]?(ve| have) (run out|reached)/i,/rate limit/i,/not available in your (country|region)/i,/unable to (generate|complete)/i,/quota (exceeded|reached)/i,/content (policy|guidelines)/i],
} as const;

export interface FlowClassification { state: FlowState; reason: string; matchedSignals: string[]; composer?: ProbedElement; submit?: ProbedElement; primaryAction?: ProbedElement; errorText?: string; url: string; title: string; }
const COMPOSER_MIN_SCORE = 25;
function matchAny(patterns: readonly RegExp[], value: string): RegExp | undefined { if (!value) return undefined; return patterns.find((pattern) => pattern.test(value)); }
function elementHaystack(el: ProbedElement): string { return [el.name,el.ariaLabel??"",el.placeholder??"",el.text,el.attrs["aria-label"]??""].filter(Boolean).join(" | "); }
function area(el: ProbedElement): number { return el.rect.width * el.rect.height; }
function centre(el: ProbedElement): {x:number;y:number} { return {x:el.rect.x+el.rect.width/2,y:el.rect.y+el.rect.height/2}; }

export function findComposer(report: PageProbeReport): ProbedElement | undefined {
  const candidates=report.elements.filter((el)=>el.visible&&el.editable&&!el.disabled&&(el.role==="textbox"||el.role==="searchbox"||el.tag==="textarea"||el.attrs["contenteditable"]!==undefined));
  let best:{el:ProbedElement;score:number}|undefined;
  for(const el of candidates){const haystack=elementHaystack(el);let score=0;if(matchAny(FLOW_SIGNALS.promptHint,haystack))score+=45;if(el.role==="searchbox"||matchAny(FLOW_SIGNALS.searchHint,haystack))score-=60;if(el.tag==="textarea"||el.attrs["contenteditable"]!==undefined)score+=15;score+=Math.min(30,area(el)/800);if(el.rect.y>200)score+=12;if(el.rect.width>300)score+=8;if(!el.inViewport)score-=10;if(!best||score>best.score)best={el,score};}
  return best&&best.score>=COMPOSER_MIN_SCORE?best.el:undefined;
}
export function findSubmit(report: PageProbeReport, composer?: ProbedElement): ProbedElement|undefined {const candidates=report.elements.filter((el)=>el.visible&&(el.role==="button"||el.role==="link"||el.tag==="button")&&!el.editable);const cc=composer?centre(composer):undefined;let best:{el:ProbedElement;score:number}|undefined;for(const el of candidates){const h=elementHaystack(el);let score=0;if(matchAny(FLOW_SIGNALS.submitHint,h))score+=50;if(el.type==="submit")score+=25;if(matchAny(FLOW_SIGNALS.submitAvoid,h))score-=60;if(el.disabled)score-=20;if(cc){const p=centre(el);score+=Math.max(0,35-Math.hypot(p.x-cc.x,p.y-cc.y)/20);}if(!best||score>best.score)best={el,score};}return best&&best.score>10?best.el:undefined;}

// Flow uses clickable cards/divs for some home controls, notably "+ New project".
// The probe already proves these are interactive via role/tabindex/aria-label, so
// do not require the underlying tag to literally be button/a.
export function findAction(report: PageProbeReport,hints:readonly RegExp[]):ProbedElement|undefined {let best:{el:ProbedElement;score:number}|undefined;for(const el of report.elements){if(!el.visible||el.disabled||el.editable)continue;const interactive=el.role==="button"||el.role==="link"||el.tag==="button"||el.tag==="a"||el.attrs["tabindex"]!==undefined||!!el.ariaLabel;if(!interactive)continue;const hit=matchAny(hints,elementHaystack(el));if(!hit)continue;const score=100-hints.indexOf(hit)*5+Math.min(20,area(el)/500);if(!best||score>best.score)best={el,score};}return best?.el;}
function textSignals(report:PageProbeReport,patterns:readonly RegExp[]):string[]{const hs=[report.visibleText,...report.liveRegions];const hits:string[]=[];for(const p of patterns)for(const h of hs){const m=h.match(p);if(m){hits.push(m[0]);break;}}return hits;}

export function classifyFlowState(report:PageProbeReport):FlowClassification {const base={url:report.url,title:report.title};if(FLOW_SIGNALS.loginUrl.test(report.url))return{...base,state:"LOGIN_REQUIRED",reason:`URL is a Google account/consent screen (${report.url})`,matchedSignals:["loginUrl"]};const composer=findComposer(report);const submit=findSubmit(report,composer);const generating=textSignals(report,FLOW_SIGNALS.generatingText);const errors=textSignals(report,FLOW_SIGNALS.errorText);const ready=textSignals(report,FLOW_SIGNALS.readyText);if(generating.length>0||(report.media.progressBars>0&&composer))return{...base,state:"GENERATING",reason:generating.length?`Generation in progress: "${generating[0]}"`:"A progress indicator is active",matchedSignals:generating.length?generating:["progressbar"],composer,submit};if(errors.length>0)return{...base,state:"ERROR",reason:`Flow reported an error: "${errors[0]}"`,matchedSignals:errors,errorText:errors.join(" | "),composer,submit};if(composer){const hasResult=report.media.playableVideos>0||ready.length>0;if(hasResult)return{...base,state:"CLIP_READY",reason:ready.length?`Finished clip is available: "${ready[0]}"`:`${report.media.playableVideos} playable video element(s) present`,matchedSignals:ready.length?ready:["playableVideos"],composer,submit};return{...base,state:"GENERATION_UI",reason:`Prompt composer discovered: ${composer.role} "${composer.name}" at ${composer.cssPath}`,matchedSignals:["composer"],composer,submit};}
  const workspaceAction=findAction(report,FLOW_SIGNALS.workspaceCta);if(workspaceAction)return{...base,state:"WORKSPACE",reason:`Project workspace control discovered: "${workspaceAction.name||workspaceAction.text}" at ${workspaceAction.cssPath}`,matchedSignals:["workspaceCta"],primaryAction:workspaceAction};const landingAction=findAction(report,FLOW_SIGNALS.landingCta);if(landingAction)return{...base,state:"LANDING",reason:`Public Flow landing page; entry control "${landingAction.name}" at ${landingAction.cssPath}`,matchedSignals:["landingCta"],primaryAction:landingAction};if(textSignals(report,FLOW_SIGNALS.workspaceText).length>0)return{...base,state:"WORKSPACE",reason:"Project list/home copy is on screen but no create control could be discovered",matchedSignals:["workspaceText"]};const loginAction=findAction(report,FLOW_SIGNALS.loginText);if(loginAction||textSignals(report,FLOW_SIGNALS.loginText).length>0)return{...base,state:"LOGIN_REQUIRED",reason:loginAction?`Sign-in control is the only way forward: "${loginAction.name}"`:"Sign-in copy is on screen and no Flow controls were found",matchedSignals:["loginText"],primaryAction:loginAction};if(report.readyState!=="complete"||report.elements.length<3)return{...base,state:"LOADING",reason:`Page is still coming up (readyState=${report.readyState}, ${report.elements.length} visible controls)`,matchedSignals:[]};return{...base,state:"UNKNOWN",reason:`No known Flow screen matched (${report.elements.length} visible controls, ${report.hiddenInteractiveCount} hidden)`,matchedSignals:[]};}
export function toFlowStates(values:readonly string[]|undefined,fallback:FlowState[]=[]):FlowState[]{if(!values||values.length===0)return fallback;const known=new Set<string>(FLOW_STATES);const bad=values.filter((v)=>!known.has(v));if(bad.length)throw new Error(`Unknown Flow state(s) ${bad.join(", ")}. Valid states: ${FLOW_STATES.join(", ")}`);return values as FlowState[];}
