"use server";

import { redirect } from "next/navigation";
import { dbConnect } from "@/lib/db";
import { Automation, Task, Workflow, WorkflowVersion } from "@bos/database";
import { buildVideoStudioWorkflow } from "@/lib/videoStudioWorkflow";

export async function runIdeaToFlowVideo(formData: FormData) {
  await dbConnect();
  const idea = String(formData.get("idea") ?? "").trim();
  const browserProfileId = String(formData.get("browserProfileId") ?? "").trim();
  if (idea.length < 5) throw new Error("Please enter a short video idea.");
  if (!browserProfileId) throw new Error("Choose a browser profile logged in to both ChatGPT and Google Flow.");

  const workflow = await Workflow.create({
    name: `Video Studio - ${idea.slice(0, 48)}`,
    description: "API-free ChatGPT web -> state-aware Google Flow clip-by-clip video production",
    status: "published",
    currentVersion: 1,
  });
  const version = await WorkflowVersion.create({
    workflowId: workflow._id,
    version: 1,
    definition: buildVideoStudioWorkflow(),
    publishedAt: new Date(),
    notes: "Generated by Video Studio; MongoDB local dispatch",
  });
  workflow.publishedVersionId = version._id;
  await workflow.save();

  const automation = await Automation.create({
    name: `Flow Video - ${idea.slice(0, 48)}`,
    description: "Video Studio runs on the local browser worker so logged-in ChatGPT and Google Flow sessions can be used.",
    slug: `flow-video-${Date.now().toString(36)}`,
    workflowId: workflow._id,
    browserProfileId,
    status: "active",
    enabled: true,
  });

  // executionTarget "local" keeps this on the Windows worker's MongoDB poll —
  // no Redis, no Render queue, so cloud automations are untouched.
  const task = await Task.create({
    automationId: automation._id,
    workflowId: workflow._id,
    workflowVersionId: version._id,
    status: "QUEUED",
    input: { idea, executionTarget: "local" },
    browserProfileId,
    source: "dashboard",
  });

  redirect(`/tasks/${task._id}`);
}
