import { describe, expect, it } from "vitest";
import { regenerateDefinition, VIDEO_STUDIO_GENERATOR, WORKFLOW_GENERATORS } from "./workflowGenerators";
import { validateWorkflowDefinition, workflowDefinitionSchema } from "@bos/shared";

describe("regenerateDefinition", () => {
  it("replays a hand-built workflow rather than rebuilding it", () => {
    // A workflow somebody drew and published has a life of its own: replaying
    // the exact version that ran is the whole point of versioning it.
    expect(regenerateDefinition(undefined)).toBeNull();
    expect(regenerateDefinition(null)).toBeNull();
    expect(regenerateDefinition("")).toBeNull();
  });

  it("ignores a generator name it does not know", () => {
    // A workflow generated by something since removed still has to be runnable.
    expect(regenerateDefinition("some-generator-that-was-deleted")).toBeNull();
  });

  it("rebuilds a Video Studio workflow from the current source", () => {
    const definition = regenerateDefinition(VIDEO_STUDIO_GENERATOR);
    expect(definition).not.toBeNull();
    expect(() => workflowDefinitionSchema.parse(definition)).not.toThrow();
    expect(validateWorkflowDefinition(definition!)).toEqual([]);
  });

  it("picks up fixes that shipped after an old run was stored", () => {
    // This is the failure that motivated it: retrying an old task replayed a
    // snapshot from before these landed, so a fixed bug came back verbatim.
    const definition = regenerateDefinition(VIDEO_STUDIO_GENERATOR)!;
    const types = definition.nodes.map((node) => node.type);
    const ids = definition.nodes.map((node) => node.id);

    // The manual sign-in gate.
    expect(definition.startNodeId).toBe("manual_sign_in");
    expect(types).toContain("WAIT_FOR_LOGIN");
    // Parsing in the worker rather than inside the page.
    expect(types).toContain("PARSE_JSON");
    expect(ids).toContain("collect_plan_reply");
    // And no in-page JSON.parse anywhere, which is what threw the old
    // "ChatGPT returned malformed JSON" straight out of page.evaluate.
    const scripts = definition.nodes.map((node) => String(node.config.script ?? "")).join("\n");
    expect(scripts).not.toContain("JSON.parse");
    expect(scripts).not.toContain("malformed JSON");
  });

  it("exposes every generator through the registry", () => {
    expect(Object.keys(WORKFLOW_GENERATORS)).toContain(VIDEO_STUDIO_GENERATOR);
    for (const [name, build] of Object.entries(WORKFLOW_GENERATORS)) {
      expect(validateWorkflowDefinition(build()), `${name} must emit a valid workflow`).toEqual([]);
    }
  });
});
